apiVersion: v1
kind: Secret
metadata:
  name: auth-admin-secret
  namespace: mlflow
type: Opaque
stringData:
  username: "admin"
  password: "admin-password"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-database-secret
  namespace: mlflow
type: Opaque
stringData:
  username: "mlflow"
  password: "mlflow_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-secret
  namespace: mlflow
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "a1b2c3d4"
  AWS_SECRET_ACCESS_KEY: "a1b2c3d4"
