apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth-secret
  namespace: db
type: Opaque
stringData:
  mongodb-root-password: "test123"
  mongodb-initial-primary-root-password: "test123"
  mongodb-passwords: "test123"
  readonly-password: "readonly"
  mongodb-replica-set-key: "aPUyPEHSlTdyYwhCM8YeK96sgARMqpFCi5Jq40yoyjQ="

