apiVersion: v1
kind: Secret
metadata:
  name: postgres-database-secret
  namespace: data-platform
type: Opaque
stringData:
  username: "mlflow"
  postgres-password: "mlflow_password"
  password: "mlflow_password"
